data: '/content/drive/My Drive/cnndm_data/cnndm_part1'
save_model: 'content/drive/My Drive/cnndm_models/cnndm_part1'

layers: 4
rnn_size: 512
word_vec_size: 512
max_grad_norm: 0
encoder_type: transformer
decoder_type: transformer
position_encoding: True

share_embeddings: True
copy_attn: True

optim: adam
dropout: 0.2
param_init: 0
warmup_steps: 8000
learning_rate: 2
decay_method: noam
label_smoothing: 0.1
adam_beta2: 0.998

batch_size: 4096
batch_type: tokens
normalization: tokens

max_generator_batches: 2

train_steps: 200000
accum_count: 4

param_init_glorot: True
world_size: 2
gpu_ranks: [0, 1]

my_shuffle: True
