save_model: 'giga_pt1/models/giga_halfsplit_pt1_nocov'
data: 'giga_pt1/data/giga_halfsplit_pt1'
train_from: 'giga_pt1/models/giga_halfsplit_pt1_nocov_step_88734.pt'
word_vec_size: 512
encoder_type: brnn
decoder_type: rnn
bridge: True
layers: 1
rnn_size: 512

# coverage_attn: False

copy_attn: True
reuse_copy_attn: True
global_attention: mlp

# copy_loss_by_seqlength: True
# lambda_coverage: 1.0

train_steps: 177468
valid_steps: 7395
save_checkpoint_steps: 14789
batch_size: 128
valid_batch_size: 128

max_grad_norm: 10
dropout: 0.1

optim: adam
learning_rate: 0.00025
# adagrad_accumulator_init: 0.1
start_decay_steps: 44367
learning_rate_decay: 0.5
decay_steps: 14789

seed: 777
world_size: 1
gpu_ranks:
- 0
