save_model: '/content/drive/My Drive/train_models/giga_halfsplit_pt2_large'
data: '/content/drive/My Drive/train_data/giga_halfsplit_pt2'
train_from: '/content/drive/My Drive/train_models/giga_halfsplit_pt2_large_step_59156.pt'
word_vec_size: 512
encoder_type: brnn
bridge: True
layers: 2
rnn_size: 256

coverage_attn: True

copy_attn: True
reuse_copy_attn: True
global_attention: mlp

copy_loss_by_seqlength: True
lambda_coverage: 1.0

train_steps: 177468
valid_steps: 14789
save_checkpoint_steps: 14789
batch_size: 128
valid_batch_size: 128

max_grad_norm: 5
dropout: 0.1

optim: adadelta
learning_rate: 1
adagrad_accumulator_init: 0.1
start_decay_steps: 775856
learning_rate_decay: 1
decay_steps: 775856

seed: 777
world_size: 1
gpu_ranks:
- 0
