save_model: '/content/drive/My Drive/models'
data: '/content/drive/My Drive/giga_processed/giga_halfsplit'
word_vec_size: 128
encoder_type: brnn
bridge: True
layers: 2
rnn_size: 256

coverage_attn: True

copy_attn: True
reuse_copy_attn: True
global_attention: mlp

copy_loss_by_seqlength: True
lambda_coverage: 1.0

train_steps: 25844
valid_steps: 2000
early_stopping: 5
early_stopping_criteria: ppl
batch_size: 64
valid_batch_size: 64

max_grad_norm: 2
dropout: 0.1

optim: adagrad
learning_rate: 0.15
adagrad_accumulator_init: 0.1

seed: 777
world_size: 1
gpu_ranks:
- 0
