batch_size: 20
beam_size: 10
model: /home/hansonlu/myOpenNMT/models/gigaword_copy_acc_51.78_ppl_11.71_e20.pt
src: /home/hansonlu/myOpenNMT/data/giga/small_input.txt
output: /home/hansonlu/myOpenNMT/testout/small_out.txt
verbose: True
